---
development:
  cloud_name: owenabrams
  api_key: '857812198178223'
  api_secret: xInrkT6IzY5qpNqDiRWIvEovuCs
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: owenabrams
  api_key: '857812198178223'
  api_secret: xInrkT6IzY5qpNqDiRWIvEovuCs
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: owenabrams
  api_key: '857812198178223'
  api_secret: xInrkT6IzY5qpNqDiRWIvEovuCs
  enhance_image_tag: true
  static_file_support: false
